#
# Check that the lightcone_io test suite still works with this
# version of hdfstream.
#

name: Integration test for swiftsimio

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out hdfstream module
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install hdfstream module
      run: |
        pip install .

    - name: Clone swiftsimio module
      uses: actions/checkout@v4
      with:
        repository: SWIFTSIM/swiftsimio
        path: downstream/swiftsimio
        ref: master

    - name: Install swiftsimio module
      run: |
        pip install "./downstream/swiftsimio[dev]"

    - name: Preload swiftsimio test data files
      working-directory: ./downstream/swiftsimio
      run: |
        python -c "from tests.conftest import preload_test_data; preload_test_data()"

    - name: Start hdfstream service with swiftsimio test data mounted
      uses: ./.github/actions/start-hdfstream
      with:
        data-dir: ./downstream/swiftsimio/test_data
        virtual-prefix: test_data
        image: ghcr.io/jchelly/hdfstream-api:0.0.6

    - name: Test swiftsimio with pytest
      working-directory: ./downstream/swiftsimio
      run: |
        pytest --hdfstream-server=http://localhost:8080/hdfstream

    - name: Stop hdfstream service
      uses: ./.github/actions/stop-hdfstream
      if: always()
